repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.14
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check .
        language: python
